[build]
  # Build komutları
  base = "client"
  command = "npm install && npm run build"
  publish = "build"

[build.environment]
  # Node.js versiyonu
  NODE_VERSION = "18"

# SPA routing için redirect ayarları
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy ayarları (backend için)
[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.com/api/:splat"
  status = 200
  force = true

# Socket.IO proxy
[[redirects]]
  from = "/socket.io/*"
  to = "https://your-backend-url.com/socket.io/:splat"
  status = 200
  force = true

# Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Static assets caching
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 